apiVersion: v1
kind: Service
metadata:
  name: rospub
spec:
  selector:
    func: ros-pub
#headless
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros-pub
spec:
  replicas: 1
  selector:
    matchLabels:
      func: ros-pub
  template:
    metadata:
      labels:
        func: ros-pub
    spec:
      hostname: rospub
      containers:
      - name: pub
        image: gabbro:30500/ros:pubsub
        imagePullPolicy: Never
        env:
        - name: ROS_MASTER_URI
          value: http://roscore:11311/
        command:
        - /bin/bash
        - -c
        - "sleep 1 && source /opt/ros/devel/setup.bash && rosrun roscpp_tutorials talker"
